[package]
name = "dealer-r"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.12.1"
config = { version = "0.15", features = ["yaml"] }
config-rs = "0.1.3"
serde = { version = "1.0", features = ["derive"] }
